version: '3.6'
services:
    iris:
        container_name: iris
        build:
            context: ./iris
            dockerfile: Dockerfile
        restart: unless-stopped
        command: --check-caps false
        ports:
            - 52773:52773
            - 53773:53773
            - 1972:1972/tcp
            - 1972:1972/udp
        #volumes:
            #- ./:/irisrun/repo
        #links:
        #    - iris:iris
            
        networks:
          - psql-pgql


    atlas:
        container_name: atlas
        build:
            context: ./atlas
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            WEBAPI_URL: http://webapi:8080/WebAPI/
        expose:
            - 80
        ports:
            - 8081:80
        #links:
        #    - webapi:webapi
        networks:
            - psql-pgql
        
        depends_on:
            - webapi
            
          
    webapi:
        container_name: webapi
        build:
            context: ./webapi
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - 8080:8080
        #volumes:
        #    - ./:/irisrun/repo
        #links:
        #    - postgresql:postgresql
        depends_on:
            - postgresql
            - iris
        networks:
          - psql-pgql
          
    postgresql:
        container_name: postgresql
        restart: always
        image: psql
        build:
          context: ./postgresql
        #volumes:
        #  - ./db/data/:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234  # To be moved to environment file
            POSTGRES_DATABASE: omop
            POSTGRES_HOST_AUTH_METHOD: md5
            POSTGRES_PASSWORD_ENCRYPTION: md5
        expose:
          - 5432
        ports:
          - 5432:5432
        networks:
          - psql-pgql
          
    
         
networks:
    psql-pgql: